export enum QuizReducerConstants {
  QUIZ_START_LOADING = 'QUIZ_START_LOADING',
  QUIZ_STATUS_SUCCESS = 'QUIZ_STATUS_SUCCESS',
  QUIZ_STATUS_FAILURE = 'QUIZ_STATUS_FAILURE',
  QUIZ_STATUS_EMPTY = 'QUIZ_STATUS_EMPTY',
  QUIZ_ANSWER_SUCCESS = 'QUIZ_ANSWER_SUCCESS',
}
